# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/hdl/pins.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0 || ORIG_REF_NAME==design_1_clk_wiz_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_1/design_1_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_1 || ORIG_REF_NAME==design_1_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_0_0/design_1_debouncer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debouncer_0_0 || ORIG_REF_NAME==design_1_debouncer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_1_0/design_1_debouncer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debouncer_1_0 || ORIG_REF_NAME==design_1_debouncer_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_edge_detector_0_0/design_1_edge_detector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_edge_detector_0_0 || ORIG_REF_NAME==design_1_edge_detector_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_edge_detector_1_0/design_1_edge_detector_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_edge_detector_1_0 || ORIG_REF_NAME==design_1_edge_detector_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi4stream_spi_master_0_0/design_1_axi4stream_spi_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi4stream_spi_master_0_0 || ORIG_REF_NAME==design_1_axi4stream_spi_master_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_digilent_jstk2_0_0/design_1_digilent_jstk2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_digilent_jstk2_0_0 || ORIG_REF_NAME==design_1_digilent_jstk2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dual_i2s_0_2/design_1_axis_dual_i2s_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_dual_i2s_0_2 || ORIG_REF_NAME==design_1_axis_dual_i2s_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dual_moving_average_0_0/design_1_dual_moving_average_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dual_moving_average_0_0 || ORIG_REF_NAME==design_1_dual_moving_average_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_led_controller_0_0/design_1_led_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_led_controller_0_0 || ORIG_REF_NAME==design_1_led_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mute_0_0/design_1_mute_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mute_0_0 || ORIG_REF_NAME==design_1_mute_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_volume_controller_0_0/design_1_volume_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_volume_controller_0_0 || ORIG_REF_NAME==design_1_volume_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_balance_controller_0_0/design_1_balance_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_balance_controller_0_0 || ORIG_REF_NAME==design_1_balance_controller_0_0} -quiet] -quiet

# XDC: c:/Users/mario/Desktop/Group_11A_assignement3.xpr/LAB3_Loopback/LAB3_Loopback.gen/sources_1/bd/design_1/design_1_ooc.xdc
